version: '3.4'

services:
  mongo:
    image: mongo

  redis:
    image: redis:alpine

  postgres:
    image: postgres

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest

  pgadmin:
    image: dpage/pgadmin4

  rabbitmq:
    image: rabbitmq:3-management-alpine

  mongo.express:
    image: mongo-express

  portainer:
    image: portainer/portainer-ce

  elasticsearch:
    image: elasticsearch:7.9.2

  graylog:
    image: graylog/graylog:4.1-jre11

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

volumes:
  mongo_data:
  redis_data:
  portainer_data:
  postgres_data:
  pgadmin_data:
  sqlserver_data:
  rabbitmq_data:
  graylog_data: